---
- hosts: validator-dev-ansible
  remote_user: root
  gather_facts: false

  tasks:

  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Install Validator dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
       - git
       - apache2
       - php
       - libapache2-mod-php

  - name: Clone the validator git repo
    git:
      repo: https://github.com/IATI/IATI-Public-Validator.git
      dest: /var/www/html/IATI-Public-Validator
      update: yes

  - name: Create an upload directory
    file:
      path: /var/www/html/IATI-Public-Validator/upload
      state: directory
      mode: 0755

  - name: Make a copy of the settings.php file
    copy:
      remote_src: yes
      src: /var/www/html/IATI-Public-Validator/example.settings.php
      dest: /var/www/html/IATI-Public-Validator/settings.php

  - name: Replace default settings with appropriate variables
    replace:
      path: /var/www/html/IATI-Public-Validator/settings.php
      regexp: '$host = "http://localhost/Webs/validate-me/";'
      replace: '$host = "123";'
      backup: yes
