---
- hosts: iati-website-dev
  remote_user: root
  roles:
    - common/install_default_packages
    - common/postgres/postgres_install
    - common/create_user
    - wagtail/wagtail_setup
    - common/postgres/postgres_recover_backup

  vars:
    custom_user: iati-website
    custom_database_name: iati-db
    db_uri: postgres:///{{ custom_database_name }}
    db_user: "{{ custom_user }}"
    requirements_file: requirements.txt
    app_name: iati
