---
- include_role:
    name: common/install_dependencies

- name: Enable mod_headers
  apache2_module:
    name: headers
    state: present

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Copy apache2 config file to sites-available
  copy:
    remote_src: no
    src: "{{ apache2_conf_template }}"
    dest: "{{ apache2_conf_destination }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
